-- 2022년 1월 판매 기준 / 저자별_카테고리별 매출액
-- 출력: 저자 ID, 저자명, 카테고리, 매출액
-- 저자 ID 오름차순, 카테고리 내림차순
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS BS JOIN BOOK AS B USING(BOOK_ID) JOIN AUTHOR AS A USING(AUTHOR_ID)
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') LIKE '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC