-- 더이상 업그레이드할 수 없는 아이템
-- ID 내림차순
SELECT IT.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE AS IT JOIN ITEM_INFO AS II
USING (ITEM_ID)
WHERE IT.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL) 
ORDER BY ITEM_ID DESC