-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
-- 매출액 내림, 상품코드 오름
WITH OFFSUM AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS HAP
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_CODE, (P.PRICE*O.HAP)AS SALES
FROM PRODUCT AS P JOIN OFFSUM AS O
USING(PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE