-- 판매날짜, 상품ID, 유저ID, 판매량
-- 2022년 3월 온/오프
-- 오프 USER_ID = NULL
-- 판매일 오름차순, 상품 ID 오름차순, 유저 ID 오름차순
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
    
UNION
    
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID