-- 자동차 종류 '세단'or'SUV'
-- 2022.11.01~2022.11.30
-- 30일간 대여 금액: 50이상 200미만
-- =>자동차ID, 자동차 종류, 대여 금액
-- 대여 금액 내림차순, 자동차 종류 오름차순, 자동차 ID 내림차순

WITH CARTYPE AS (
    SELECT CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('SUV','세단')
),
SE_DATE AS (
    SELECT  CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE<='2022-11-30' AND END_DATE>='2022-11-01'
),
THIRTY_MONEY AS (
    SELECT C.CAR_ID, FLOOR(C.DAILY_FEE*(1-P.DISCOUNT_RATE/100)*30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
        JOIN (
            SELECT * 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE='30일 이상'
        ) AS P
        USING (CAR_TYPE)
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM CARTYPE 
    JOIN THIRTY_MONEY USING(CAR_ID)
WHERE 500000<=FEE AND FEE<2000000 
    AND CAR_ID NOT IN (SELECT CAR_ID FROM SE_DATE) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC