-- 평균 길이 33CM 이상 
-- 잡은 수, 최대 길이, 물고기 종류
-- 종류 오름차순
-- 10CM 이하는 10로 취급해서 길이 구하기

WITH LEN AS (
    SELECT FISH_TYPE, AVG(IF(LENGTH<=10 OR LENGTH IS NULL,10,LENGTH)) AS AVGLEN, MAX(IF(LENGTH<=10 OR LENGTH IS NULL,10,LENGTH)) AS MAXLEN, COUNT(*) AS CNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT CNT AS FISH_COUNT, MAXLEN AS MAX_LENGTH, FISH_TYPE
FROM LEN
WHERE AVGLEN>=33
ORDER BY FISH_TYPE



