-- 개체 크기 내림차순
-- ID, COLONY_NAME
-- ID 오름차순
SELECT A.ID,
    CASE
        WHEN A.RK/A.CNT <=0.25 THEN 'CRITICAL'
        WHEN A.RK/A.CNT <=0.50 THEN 'HIGH'
        WHEN A.RK/A.CNT <=0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RK, COUNT(*) OVER() AS CNT
    FROM ECOLI_DATA
    ) AS A
ORDER BY A.ID;