-- => ID, COLONY_NAME(분류된 이름)
-- ID 오름차순
SELECT ID, CASE
    WHEN R<= CNT*0.25 THEN 'CRITICAL'
    WHEN R<= CNT*0.5 THEN 'HIGH'
    WHEN R<= CNT*0.75 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, 
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS CNT
    FROM ECOLI_DATA
) AS E
ORDER BY ID