-- 년, 월, 성별 별 상품 구매 회원 수
-- 년, 월, 성별 오름차순
-- 성별 없으면 제외 / 같은 연월일 한 고객의 여러번 구매는 한 번으로 취급
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO AS U JOIN ONLINE_SALE AS O
USING (USER_ID)
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER