-- 중고 거래 게시물 3건 이상
-- 사용자 ID, 닉네임, 전체 주소, 전화번호
-- 전체 주소: 시,도로명,상세 / 전화번호: 하이픈 포함
-- 회원 ID 내림차순
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소', CONCAT(LEFT(TLNO,3),'-',SUBSTR(TLNO,4,4),'-',RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_USER JOIN (
    SELECT WRITER_ID AS W_ID, COUNT(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*)>=3
    ) AS B
ON USER_ID = B.W_ID
ORDER BY USER_ID DESC
