-- 자식 없는 개체 수, 세대
-- 세대 오름차순
WITH RECURSIVE R AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, R.GEN+1 AS GEN
    FROM ECOLI_DATA AS E JOIN R
    ON R.ID = E.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GEN AS GENERATION
FROM R
WHERE ID NOT IN (
    SELECT PARENT_ID FROM R WHERE PARENT_ID IS NOT NULL
)
GROUP BY GEN
ORDER BY GEN 