-- COUNT(자식 없는 개체 수), GENERATION(세대)
-- 세대 오름차순
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION
    
    SELECT CH.ID, CH.PARENT_ID, PA.LEVEL+1 AS LEVEL
    FROM ECOLI_DATA AS CH JOIN GEN AS PA
    ON CH.PARENT_ID = PA.ID
)

SELECT COUNT(*) AS COUNT, LEVEL AS GENERATION
FROM GEN
WHERE ID NOT IN (SELECT PARENT_ID FROM GEN 
                WHERE PARENT_ID IS NOT NULL)
GROUP BY LEVEL
ORDER BY LEVEL