-- => ID, 분류(SIZE)
-- 크기 100이하 'LOW'
-- 100초과 1000이하 'MEDIUM'
-- 1000초과 'HIGH'
-- ID 오름차순
SELECT ID, (
    CASE 
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY <=1000 THEN 'MEDIUM'
    ELSE 'HIGH'
    END
) AS SIZE
FROM ECOLI_DATA

