-- 크기가 100 이하라면 'LOW', 100 초과 1000 이하라면 'MEDIUM', 1000 초과라면 'HIGH
-- ID(ID) 와 분류(SIZE)를 출력
-- ID 오름
SELECT ID, (
    CASE WHEN SIZE_OF_COLONY <=100 THEN 'LOW'
    WHEN SIZE_OF_COLONY <=1000 THEN 'MEDIUM'
    ELSE 'HIGH'
    END
    ) AS SIZE
FROM ECOLI_DATA 
ORDER BY ID