-- 자동차 종류 트럭, 대여 기록 별 대여 금액 구하기
-- 대여 기록 ID, 대여금액 리스트
-- 대여 금액 내림차순, ID 내림차순
WITH CAR AS (
SELECT H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS DURDATE,
    CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1>=7 THEN '7일 이상'
        ELSE NULL
        END AS DURATION_TYPE
    , C.DAILY_FEE, C.CAR_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
    JOIN CAR_RENTAL_COMPANY_CAR AS C USING(CAR_ID)
WHERE C.CAR_TYPE = '트럭')

SELECT CAR.HISTORY_ID, FLOOR(CAR.DAILY_FEE*(1-IFNULL(D.DISCOUNT_RATE,0)/100)*CAR.DURDATE) AS FEE
FROM CAR LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
USING (DURATION_TYPE,CAR_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC