-- 시간대별 입견 건 수
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR<23
)
SELECT T.HOUR, COUNT(A.DATETIME) AS COUNT
FROM TIME AS T LEFT OUTER JOIN ANIMAL_OUTS AS A
ON DATE_FORMAT(A.DATETIME, '%H')=T.HOUR
GROUP BY HOUR
