-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
-- 총 거래금액 오름차순
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE)
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON U.USER_ID = B.WRITER_ID
WHERE  B.STATUS='DONE'
GROUP BY U.USER_ID
HAVING SUM(B.PRICE)>=700000
ORDER BY SUM(B.PRICE)