-- 2022년 4월 13일 취소되지 않은 cs 진료내역 조회
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시
-- 진료예약일시 오름차순
SELECT AP.APNT_NO, PT.PT_NAME, PT.PT_NO, DR.MCDP_CD, DR.DR_NAME, AP.APNT_YMD
FROM PATIENT AS PT, DOCTOR AS DR, APPOINTMENT AS AP
WHERE PT.PT_NO = AP.PT_NO AND AP.MDDR_ID = DR.DR_ID
AND DR.MCDP_CD = 'CS' AND AP.APNT_CNCL_YN = 'N' 
AND YEAR(AP.APNT_YMD)=2022 AND MONTH(AP.APNT_YMD)=4 AND DAY(AP.APNT_YMD)=13
ORDER BY AP.APNT_YMD