-- 종류'세단', 10월 대여 시작한 차 ID
-- ID 중복X, ID 내림차순

SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H 
ON (C.CAR_TYPE LIKE '세단' AND C.CAR_ID=H.CAR_ID)
WHERE DATE_FORMAT(H.START_DATE,'%m')=10
ORDER BY CAR_ID DESC

