-- 2022년 10월 작성
-- => 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
-- 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS R USING(BOARD_ID)
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y-%m')='2022-10'
ORDER BY R.CREATED_DATE, B.TITLE