WITH R AS (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RA
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유'))

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM R
WHERE RA =1
ORDER BY PRICE DESC